In [55]:
import pandas as pd
import numpy as np
import datetime as dt

# Serie z NumPy

## Serie Python

In [56]:
seria_lista=pd.Series([1,2,3,4,5])

In [57]:
seria_slownik=pd.Series({'a':1, 'b':2, 'c':3,'d':4, 'e':5})

In [58]:
seria_data = pd.Series(pd.date_range(start=pd.Timestamp.today(), periods=5))
seria_data = seria_data.dt.date

## Serie NumPy

In [59]:
seria_array=pd.Series(np.array([1,2,3,4,5]))

In [60]:
seria_full=pd.Series(np.full( (5), 12 ))

In [61]:
seria_arange = pd.Series(np.arange(start=1,stop=6,step=1))

In [62]:
seria_linspace=pd.Series(np.linspace(start=1,stop=5,num=5,dtype='int16'))

In [63]:
seria_random=pd.Series(np.random.rand(5))

## Macierze NumPy

In [64]:
array_numpy = np.array([1,2,3,4,5])

In [65]:
jedynki_numpy = np.ones((3,5),dtype='int8')

In [66]:
zera_numpy = np.zeros((6,3), dtype='int8')

In [67]:
diagonal_numpy = np.eye(5)

In [68]:
macierz_full=np.full((2,5),10) 

In [69]:
zakres_numpy = np.arange(start=10, stop=30, step=1,dtype='int16')

In [70]:
losowy_numpy = np.random.rand(10,3)

In [71]:
losowy_przedzial_numpy = np.random.randint(low=1, high=10,size=(2,3))

## Proste komendy w pakiecie NumPy

In [72]:
jedynki_numpy.ndim #liczba wymiarów macierzy

2

In [73]:
zera_numpy.shape #rozmiar macierzy

(6, 3)

In [74]:
macierz_full.size #liczba elementów w macierzy

10

In [75]:
zakres_numpy.dtype #typ danych w macierzy

dtype('int16')

In [76]:
losowy_numpy.itemsize #liczba bitów dla każdej wartości w macierzy

8

In [77]:
zera_numpy.reshape(3,2,3) #zmienia 

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int8)

## Indexing/slicing/subsetting

In [107]:
np.random.seed(10) #ustawienie generatora liczb pseudolosowych, dzięki temu wszyscy mamy te same liczby losowe, ten sam generator
tablica = np.random.randint(low=1, high=100, size=(5,5))
tablica = np.random.rand(5,5)*100
tablica

array([[54.2544368 , 14.21700476, 37.33407601, 67.41336151, 44.18331744],
       [43.40139933, 61.77669785, 51.31382426, 65.03971819, 60.10389534],
       [80.52231968, 52.16471524, 90.86488808, 31.9236089 ,  9.04593493],
       [30.07000566, 11.39843619, 82.86813263,  4.68963194, 62.62871483],
       [54.75861559, 81.92869957, 19.89475397, 85.68503025, 35.16526394]])

In [79]:
tablica[4] # wiersz 5-ty z zakresu

array([54.75861559, 81.92869957, 19.89475397, 85.68503025, 35.16526394])

In [80]:
tablica[4,1] # wiersz 5-ty, wartość 2-ga

81.92869956700687

In [81]:
tablica[4,1:3] = 5 # przypisanie wartości do zakresu

In [82]:
tablica[1::2,0::2] # nieparzyste kolumny i parzyste wiersze

array([[43.40139933, 51.31382426, 60.10389534],
       [30.07000566, 82.86813263, 62.62871483]])

In [83]:
tablica[:,3] # pokazanie wartości 3-ciej we wszystkich wierszach

array([67.41336151, 65.03971819, 31.9236089 ,  4.68963194, 85.68503025])

In [84]:
tablica >50 # zwraca macierz logiczną z wartościami większymi niż 50

array([[ True, False, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False,  True, False,  True],
       [ True, False, False,  True, False]])

In [85]:
tablica[tablica>50] # zwraca listę wartości większych niż 50

array([54.2544368 , 67.41336151, 61.77669785, 51.31382426, 65.03971819,
       60.10389534, 80.52231968, 52.16471524, 90.86488808, 82.86813263,
       62.62871483, 54.75861559, 85.68503025])

In [86]:
(tablica>50) | (tablica<20) # zwraca macierz logiczną wartości większych niż 50 i mniejszych niż 20

array([[ True,  True, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [87]:
tablica[(tablica>50) | (tablica<20)] # zwraca listę wartości większych niż 50 i mniejszych niż 20

array([54.2544368 , 14.21700476, 67.41336151, 61.77669785, 51.31382426,
       65.03971819, 60.10389534, 80.52231968, 52.16471524, 90.86488808,
        9.04593493, 11.39843619, 82.86813263,  4.68963194, 62.62871483,
       54.75861559,  5.        ,  5.        , 85.68503025])

## Obliczenia matematyczne skalarne i wektorowe na macierzach NumPy

In [88]:
tablica

array([[54.2544368 , 14.21700476, 37.33407601, 67.41336151, 44.18331744],
       [43.40139933, 61.77669785, 51.31382426, 65.03971819, 60.10389534],
       [80.52231968, 52.16471524, 90.86488808, 31.9236089 ,  9.04593493],
       [30.07000566, 11.39843619, 82.86813263,  4.68963194, 62.62871483],
       [54.75861559,  5.        ,  5.        , 85.68503025, 35.16526394]])

In [89]:
dodawanie_tablica= np.add(tablica,5) # dodaje 5 do każdej wartości w tablicy

In [90]:
odejmowanie_tablica=np.subtract(tablica[0],100) # odejmuje 100 od każdej wartości z pierwszego wiersza w tablicy

In [91]:
mnożenie_tablica=np.multiply(tablica[0], tablica[4]) # mnoży element z pierwszego wiersza z elementem z ostatniego wiersza konsekutywnie

In [92]:
dzielenie_tablica=np.divide(tablica[1],1000) #dzieli każdy element z wiersza drugiego przez 1000

In [93]:
potęga_tablica = np.power(tablica[2],2) #podnosi każdy element z 3-go wiersza tablicy do potęgi 4-tej

### Inne funkcje: sqrt, sin, log, abs, ceil (up), floor (down), round

In [94]:
zaokr_w_gore_tablica = np.ceil(tablica)

In [95]:
zaokr_w_dol_tablica = np.floor(tablica)

In [96]:
zaokr_do_calk_tablica = np.round(tablica)

## Statystyki NumPy

In [97]:
średnia_tablica = np.mean(tablica) #oblicza średnią dla całej tablicy

In [98]:
średnia_kolumny_tablica = np.mean(tablica, axis=0) # średnia z każdej kolumny

In [99]:
suma_tablica = np.sum(tablica[0:2])  # suma wartości z wiersza pierwszego i drugiego

In [100]:
minimalna_w_tablicy = np.min(tablica[:,2]) # wartość minimalna wszystkie wiersze, 3-cia kolumna

In [101]:
maksymalna_w_tablicy = np.max(tablica, axis=1) # wyszukuje najwyższe wartości z każdego wiersza

In [102]:
suma_tablica = np.sum(tablica[tablica<=5]) # suma wartości <=5

In [103]:
wariancja_tablica = np.var(tablica) # wariancja z tablicy

In [104]:
odch_std_tablica =np.std(tablica)

In [105]:
korelacja_tablica =np.corrcoef(tablica)

# PANDAS

In [108]:
import pandas as pd

In [111]:
df = pd.read_excel('baza.xlsx')
df

Imię  Wiek   Pensja  Lata pracy       ID
0    Muminek    20  5946,21           1  MU-60-K
1    Mamusia    45   5578,5          25  MA-67-A
2      Tatuś    45   3071,6          25  TA-29-Ś
3    Mała Mi    18  5216,36           2  MA-53-I
4  Włóczykij    25  3853,83           6  W?-70-J
5    Migotka    22  3243,95           5  MI-89-A
6    Migotek    23  3175,94           5  MI-39-K
7       Buka    50   5731,6          35  BU-81-A
8      Topik    40   8167,8          20  TO-73-K
9     Topcia    40  8852,16          18  TO-53-A